<?php

//--- Universal Constants ---
const SEC_IN_DAY = 							(60 * 60 * 24);

//--- Financial Constants ---
$START_DATE_STRING_FINANCIAL = 			'June 1st 2018';

$ANNUAL_INCOME_TARGET = 				74250;	// If hit, annual After Tax Income ~$55,000
$ANNUAL_EXPENDITURE_TARGET =			15000;	// If hit and Income Target hit...net worth contribution ~$40,000

$AVG_DAILY_INCOME_TARGET = 				number_format($ANNUAL_INCOME_TARGET / 365, 2);
$AVG_DAILY_EXPENDITURE_TARGET = 		number_format($ANNUAL_EXPENDITURE_TARGET / 365, 2);

$HOURLY_WAGE_SEAL = 					21.63;
$HOURLY_WAGE_RICKS = 					7.50;
$HOURLY_WAGE_TARGET =					26;

$WEEKLY_INCOME_TARGET = 				$AVG_DAILY_INCOME_TARGET * 7;
$WEEKLY_EXPENDITURE_TARGET = 			$AVG_DAILY_EXPENDITURE_TARGET * 7;
$WEEKLY_INCOME_DIFF_TARGET = 			$WEEKLY_INCOME_TARGET - $WEEKLY_EXPENDITURE_TARGET;
$WEEKLY_HOURS_TARGET = 					55;

$PRE_JUNE_RICKS_INCOME =				12914;
$ESTIMATED_AFTER_TAX_PERCENTAGE =		75;

$JUNE_1ST_DEBT =						17000;

//--- Fitness Constants ---
$START_DATE_STRING_RUNNING = 			'June 29th 2018';
$STARTING_MILE_TIME =					515; // In seconds
const MILE_TIME_TARGET =				405; // In seconds

const START_DATE_STRING_BODY_WEIGHT =	'June 4th 2018';
const STARTING_BODY_WEIGHT =			147.0; // In Pounds
const BODY_WEIGHT_TARGET =				160.0; // In Pounds

?>