<?php
	
$ANNUAL_INCOME_TARGET = 				74250;	// Annual After Tax Income ~$55,000
$ANNUAL_EXPENDITURE_TARGET =			15000;	//

$AVG_DAILY_INCOME_TARGET = 				$ANNUAL_INCOME_TARGET / 365;
$AVG_DAILY_EXPENDITURE_TARGET = 		$ANNUAL_EXPENDITURE_TARGET / 365;

$HOURLY_WAGE_SEAL = 					21.63;
$HOURLY_WAGE_RICKS = 					7.50;

$WEEKLY_INCOME_TARGET = 				1465;	// 
$WEEKLY_EXPENDITURE_TARGET = 			285;
$WEEKLY_INCOME_DIFF_TARGET = 			1180;
$WEEKLY_HOURS_TARGET = 					60;

?>